version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8080:8080
    # Important to bind/mount your codebase dir to /app dir for live reload
    environment:
      - REDIS_ADDR=redis:6379
      - LIMIT_REQUEST_PER_SECOND_DEFAULT=5
    volumes:
      - ./:/app
    depends_on:
      - redis

volumes:
  redis_data:
